let simple = {
  nodes: ['A', 'B', 'C', 'D', 'E', 'F'],
  links: [
    {from: 'A', to: 'B', w: 1.0},
    {from: 'A', to: 'C', w: 1.0},
    {from: 'A', to: 'F', w: 1.0},
    {from: 'B', to: 'A', w: 1.0},
    {from: 'B', to: 'C', w: 1.0},
    {from: 'C', to: 'A', w: 1.0},
    {from: 'C', to: 'B', w: 1.0},
    {from: 'D', to: 'E', w: 1.0},
    {from: 'D', to: 'F', w: 1.0},
    {from: 'E', to: 'F', w: 1.0},
    {from: 'E', to: 'D', w: 1.0},
    {from: 'F', to: 'E', w: 1.0},
    {from: 'F', to: 'D', w: 1.0},
    {from: 'F', to: 'A', w: 1.0}
  ]
};


let mis = {
  nodes: [
    'Myriel',
    'Napoleon',
    'Mlle.Baptistine',
    'Mme.Magloire',
    'CountessdeLo',
    'Geborand',
    'Champtercier',
    'Cravatte',
    'Count',
    'OldMan',
    'Labarre',
    'Valjean',
    'Marguerite',
    'Mme.deR',
    'Isabeau',
    'Gervais',
    'Tholomyes',
    'Listolier',
    'Fameuil',
    'Blacheville',
    'Favourite',
    'Dahlia',
    'Zephine',
    'Fantine',
    'Mme.Thenardier',
    'Thenardier',
    'Cosette',
    'Javert',
    'Fauchelevent',
    'Bamatabois',
    'Perpetue',
    'Simplice',
    'Scaufflaire',
    'Woman1',
    'Judge',
    'Champmathieu',
    'Brevet',
    'Chenildieu',
    'Cochepaille',
    'Pontmercy',
    'Boulatruelle',
    'Eponine',
    'Anzelma',
    'Woman2',
    'MotherInnocent',
    'Gribier',
    'Jondrette',
    'Mme.Burgon',
    'Gavroche',
    'Gillenormand',
    'Magnon',
    'Mlle.Gillenormand',
    'Mme.Pontmercy',
    'Mlle.Vaubois',
    'Lt.Gillenormand',
    'Marius',
    'BaronessT',
    'Mabeuf',
    'Enjolras',
    'Combeferre',
    'Prouvaire',
    'Feuilly',
    'Courfeyrac',
    'Bahorel',
    'Bossuet',
    'Joly',
    'Grantaire',
    'MotherPlutarch',
    'Gueulemer',
    'Babet',
    'Claquesous',
    'Montparnasse',
    'Toussaint',
    'Child1',
    'Child2',
    'Brujon',
    'Mme.Hucheloup',
  ],

  links: [
    {from: 'Napoleon', to: 'Myriel'},
    {from: 'Mlle.Baptistine', to: 'Myriel'},
    {from: 'Mme.Magloire', to: 'Myriel'},
    {from: 'Mme.Magloire', to: 'Mlle.Baptistine'},
    {from: 'CountessdeLo', to: 'Myriel'},
    {from: 'Geborand', to: 'Myriel'},
    {from: 'Champtercier', to: 'Myriel'},
    {from: 'Cravatte', to: 'Myriel'},
    {from: 'Count', to: 'Myriel'},
    {from: 'OldMan', to: 'Myriel'},
    {from: 'Valjean', to: 'Labarre'},
    {from: 'Valjean', to: 'Mme.Magloire'},
    {from: 'Valjean', to: 'Mlle.Baptistine'},
    {from: 'Valjean', to: 'Myriel'},
    {from: 'Marguerite', to: 'Valjean'},
    {from: 'Mme.deR', to: 'Valjean'},
    {from: 'Isabeau', to: 'Valjean'},
    {from: 'Gervais', to: 'Valjean'},
    {from: 'Listolier', to: 'Tholomyes'},
    {from: 'Fameuil', to: 'Tholomyes'},
    {from: 'Fameuil', to: 'Listolier'},
    {from: 'Blacheville', to: 'Tholomyes'},
    {from: 'Blacheville', to: 'Listolier'},
    {from: 'Blacheville', to: 'Fameuil'},
    {from: 'Favourite', to: 'Tholomyes'},
    {from: 'Favourite', to: 'Listolier'},
    {from: 'Favourite', to: 'Fameuil'},
    {from: 'Favourite', to: 'Blacheville'},
    {from: 'Dahlia', to: 'Tholomyes'},
    {from: 'Dahlia', to: 'Listolier'},
    {from: 'Dahlia', to: 'Fameuil'},
    {from: 'Dahlia', to: 'Blacheville'},
    {from: 'Dahlia', to: 'Favourite'},
    {from: 'Zephine', to: 'Tholomyes'},
    {from: 'Zephine', to: 'Listolier'},
    {from: 'Zephine', to: 'Fameuil'},
    {from: 'Zephine', to: 'Blacheville'},
    {from: 'Zephine', to: 'Favourite'},
    {from: 'Zephine', to: 'Dahlia'},
    {from: 'Fantine', to: 'Tholomyes'},
    {from: 'Fantine', to: 'Listolier'},
    {from: 'Fantine', to: 'Fameuil'},
    {from: 'Fantine', to: 'Blacheville'},
    {from: 'Fantine', to: 'Favourite'},
    {from: 'Fantine', to: 'Dahlia'},
    {from: 'Fantine', to: 'Zephine'},
    {from: 'Fantine', to: 'Marguerite'},
    {from: 'Fantine', to: 'Valjean'},
    {from: 'Mme.Thenardier', to: 'Fantine'},
    {from: 'Mme.Thenardier', to: 'Valjean'},
    {from: 'Thenardier', to: 'Mme.Thenardier'},
    {from: 'Thenardier', to: 'Fantine'},
    {from: 'Thenardier', to: 'Valjean'},
    {from: 'Cosette', to: 'Mme.Thenardier'},
    {from: 'Cosette', to: 'Valjean'},
    {from: 'Cosette', to: 'Tholomyes'},
    {from: 'Cosette', to: 'Thenardier'},
    {from: 'Javert', to: 'Valjean'},
    {from: 'Javert', to: 'Fantine'},
    {from: 'Javert', to: 'Thenardier'},
    {from: 'Javert', to: 'Mme.Thenardier'},
    {from: 'Javert', to: 'Cosette'},
    {from: 'Fauchelevent', to: 'Valjean'},
    {from: 'Fauchelevent', to: 'Javert'},
    {from: 'Bamatabois', to: 'Fantine'},
    {from: 'Bamatabois', to: 'Javert'},
    {from: 'Bamatabois', to: 'Valjean'},
    {from: 'Perpetue', to: 'Fantine'},
    {from: 'Simplice', to: 'Perpetue'},
    {from: 'Simplice', to: 'Valjean'},
    {from: 'Simplice', to: 'Fantine'},
    {from: 'Simplice', to: 'Javert'},
    {from: 'Scaufflaire', to: 'Valjean'},
    {from: 'Woman1', to: 'Valjean'},
    {from: 'Woman1', to: 'Javert'},
    {from: 'Judge', to: 'Valjean'},
    {from: 'Judge', to: 'Bamatabois'},
    {from: 'Champmathieu', to: 'Valjean'},
    {from: 'Champmathieu', to: 'Judge'},
    {from: 'Champmathieu', to: 'Bamatabois'},
    {from: 'Brevet', to: 'Judge'},
    {from: 'Brevet', to: 'Champmathieu'},
    {from: 'Brevet', to: 'Valjean'},
    {from: 'Brevet', to: 'Bamatabois'},
    {from: 'Chenildieu', to: 'Judge'},
    {from: 'Chenildieu', to: 'Champmathieu'},
    {from: 'Chenildieu', to: 'Brevet'},
    {from: 'Chenildieu', to: 'Valjean'},
    {from: 'Chenildieu', to: 'Bamatabois'},
    {from: 'Cochepaille', to: 'Judge'},
    {from: 'Cochepaille', to: 'Champmathieu'},
    {from: 'Cochepaille', to: 'Brevet'},
    {from: 'Cochepaille', to: 'Chenildieu'},
    {from: 'Cochepaille', to: 'Valjean'},
    {from: 'Cochepaille', to: 'Bamatabois'},
    {from: 'Pontmercy', to: 'Thenardier'},
    {from: 'Boulatruelle', to: 'Thenardier'},
    {from: 'Eponine', to: 'Mme.Thenardier'},
    {from: 'Eponine', to: 'Thenardier'},
    {from: 'Anzelma', to: 'Eponine'},
    {from: 'Anzelma', to: 'Thenardier'},
    {from: 'Anzelma', to: 'Mme.Thenardier'},
    {from: 'Woman2', to: 'Valjean'},
    {from: 'Woman2', to: 'Cosette'},
    {from: 'Woman2', to: 'Javert'},
    {from: 'MotherInnocent', to: 'Fauchelevent'},
    {from: 'MotherInnocent', to: 'Valjean'},
    {from: 'Gribier', to: 'Fauchelevent'},
    {from: 'Mme.Burgon', to: 'Jondrette'},
    {from: 'Gavroche', to: 'Mme.Burgon'},
    {from: 'Gavroche', to: 'Thenardier'},
    {from: 'Gavroche', to: 'Javert'},
    {from: 'Gavroche', to: 'Valjean'},
    {from: 'Gillenormand', to: 'Cosette'},
    {from: 'Gillenormand', to: 'Valjean'},
    {from: 'Magnon', to: 'Gillenormand'},
    {from: 'Magnon', to: 'Mme.Thenardier'},
    {from: 'Mlle.Gillenormand', to: 'Gillenormand'},
    {from: 'Mlle.Gillenormand', to: 'Cosette'},
    {from: 'Mlle.Gillenormand', to: 'Valjean'},
    {from: 'Mme.Pontmercy', to: 'Mlle.Gillenormand'},
    {from: 'Mme.Pontmercy', to: 'Pontmercy'},
    {from: 'Mlle.Vaubois', to: 'Mlle.Gillenormand'},
    {from: 'Lt.Gillenormand', to: 'Mlle.Gillenormand'},
    {from: 'Lt.Gillenormand', to: 'Gillenormand'},
    {from: 'Lt.Gillenormand', to: 'Cosette'},
    {from: 'Marius', to: 'Mlle.Gillenormand'},
    {from: 'Marius', to: 'Gillenormand'},
    {from: 'Marius', to: 'Pontmercy'},
    {from: 'Marius', to: 'Lt.Gillenormand'},
    {from: 'Marius', to: 'Cosette'},
    {from: 'Marius', to: 'Valjean'},
    {from: 'Marius', to: 'Tholomyes'},
    {from: 'Marius', to: 'Thenardier'},
    {from: 'Marius', to: 'Eponine'},
    {from: 'Marius', to: 'Gavroche'},
    {from: 'BaronessT', to: 'Gillenormand'},
    {from: 'BaronessT', to: 'Marius'},
    {from: 'Mabeuf', to: 'Marius'},
    {from: 'Mabeuf', to: 'Eponine'},
    {from: 'Mabeuf', to: 'Gavroche'},
    {from: 'Enjolras', to: 'Marius'},
    {from: 'Enjolras', to: 'Gavroche'},
    {from: 'Enjolras', to: 'Javert'},
    {from: 'Enjolras', to: 'Mabeuf'},
    {from: 'Enjolras', to: 'Valjean'},
    {from: 'Combeferre', to: 'Enjolras'},
    {from: 'Combeferre', to: 'Marius'},
    {from: 'Combeferre', to: 'Gavroche'},
    {from: 'Combeferre', to: 'Mabeuf'},
    {from: 'Prouvaire', to: 'Gavroche'},
    {from: 'Prouvaire', to: 'Enjolras'},
    {from: 'Prouvaire', to: 'Combeferre'},
    {from: 'Feuilly', to: 'Gavroche'},
    {from: 'Feuilly', to: 'Enjolras'},
    {from: 'Feuilly', to: 'Prouvaire'},
    {from: 'Feuilly', to: 'Combeferre'},
    {from: 'Feuilly', to: 'Mabeuf'},
    {from: 'Feuilly', to: 'Marius'},
    {from: 'Courfeyrac', to: 'Marius'},
    {from: 'Courfeyrac', to: 'Enjolras'},
    {from: 'Courfeyrac', to: 'Combeferre'},
    {from: 'Courfeyrac', to: 'Gavroche'},
    {from: 'Courfeyrac', to: 'Mabeuf'},
    {from: 'Courfeyrac', to: 'Eponine'},
    {from: 'Courfeyrac', to: 'Feuilly'},
    {from: 'Courfeyrac', to: 'Prouvaire'},
    {from: 'Bahorel', to: 'Combeferre'},
    {from: 'Bahorel', to: 'Gavroche'},
    {from: 'Bahorel', to: 'Courfeyrac'},
    {from: 'Bahorel', to: 'Mabeuf'},
    {from: 'Bahorel', to: 'Enjolras'},
    {from: 'Bahorel', to: 'Feuilly'},
    {from: 'Bahorel', to: 'Prouvaire'},
    {from: 'Bahorel', to: 'Marius'},
    {from: 'Bossuet', to: 'Marius'},
    {from: 'Bossuet', to: 'Courfeyrac'},
    {from: 'Bossuet', to: 'Gavroche'},
    {from: 'Bossuet', to: 'Bahorel'},
    {from: 'Bossuet', to: 'Enjolras'},
    {from: 'Bossuet', to: 'Feuilly'},
    {from: 'Bossuet', to: 'Prouvaire'},
    {from: 'Bossuet', to: 'Combeferre'},
    {from: 'Bossuet', to: 'Mabeuf'},
    {from: 'Bossuet', to: 'Valjean'},
    {from: 'Joly', to: 'Bahorel'},
    {from: 'Joly', to: 'Bossuet'},
    {from: 'Joly', to: 'Gavroche'},
    {from: 'Joly', to: 'Courfeyrac'},
    {from: 'Joly', to: 'Enjolras'},
    {from: 'Joly', to: 'Feuilly'},
    {from: 'Joly', to: 'Prouvaire'},
    {from: 'Joly', to: 'Combeferre'},
    {from: 'Joly', to: 'Mabeuf'},
    {from: 'Joly', to: 'Marius'},
    {from: 'Grantaire', to: 'Bossuet'},
    {from: 'Grantaire', to: 'Enjolras'},
    {from: 'Grantaire', to: 'Combeferre'},
    {from: 'Grantaire', to: 'Courfeyrac'},
    {from: 'Grantaire', to: 'Joly'},
    {from: 'Grantaire', to: 'Gavroche'},
    {from: 'Grantaire', to: 'Bahorel'},
    {from: 'Grantaire', to: 'Feuilly'},
    {from: 'Grantaire', to: 'Prouvaire'},
    {from: 'MotherPlutarch', to: 'Mabeuf'},
    {from: 'Gueulemer', to: 'Thenardier'},
    {from: 'Gueulemer', to: 'Valjean'},
    {from: 'Gueulemer', to: 'Mme.Thenardier'},
    {from: 'Gueulemer', to: 'Javert'},
    {from: 'Gueulemer', to: 'Gavroche'},
    {from: 'Gueulemer', to: 'Eponine'},
    {from: 'Babet', to: 'Thenardier'},
    {from: 'Babet', to: 'Gueulemer'},
    {from: 'Babet', to: 'Valjean'},
    {from: 'Babet', to: 'Mme.Thenardier'},
    {from: 'Babet', to: 'Javert'},
    {from: 'Babet', to: 'Gavroche'},
    {from: 'Babet', to: 'Eponine'},
    {from: 'Claquesous', to: 'Thenardier'},
    {from: 'Claquesous', to: 'Babet'},
    {from: 'Claquesous', to: 'Gueulemer'},
    {from: 'Claquesous', to: 'Valjean'},
    {from: 'Claquesous', to: 'Mme.Thenardier'},
    {from: 'Claquesous', to: 'Javert'},
    {from: 'Claquesous', to: 'Eponine'},
    {from: 'Claquesous', to: 'Enjolras'},
    {from: 'Montparnasse', to: 'Javert'},
    {from: 'Montparnasse', to: 'Babet'},
    {from: 'Montparnasse', to: 'Gueulemer'},
    {from: 'Montparnasse', to: 'Claquesous'},
    {from: 'Montparnasse', to: 'Valjean'},
    {from: 'Montparnasse', to: 'Gavroche'},
    {from: 'Montparnasse', to: 'Eponine'},
    {from: 'Montparnasse', to: 'Thenardier'},
    {from: 'Toussaint', to: 'Cosette'},
    {from: 'Toussaint', to: 'Javert'},
    {from: 'Toussaint', to: 'Valjean'},
    {from: 'Child1', to: 'Gavroche'},
    {from: 'Child2', to: 'Gavroche'},
    {from: 'Child2', to: 'Child1'},
    {from: 'Brujon', to: 'Babet'},
    {from: 'Brujon', to: 'Gueulemer'},
    {from: 'Brujon', to: 'Thenardier'},
    {from: 'Brujon', to: 'Gavroche'},
    {from: 'Brujon', to: 'Eponine'},
    {from: 'Brujon', to: 'Claquesous'},
    {from: 'Brujon', to: 'Montparnasse'},
    {from: 'Mme.Hucheloup', to: 'Bossuet'},
    {from: 'Mme.Hucheloup', to: 'Joly'},
    {from: 'Mme.Hucheloup', to: 'Grantaire'},
    {from: 'Mme.Hucheloup', to: 'Bahorel'},
    {from: 'Mme.Hucheloup', to: 'Courfeyrac'},
    {from: 'Mme.Hucheloup', to: 'Gavroche'},
    {from: 'Mme.Hucheloup', to: 'Enjolras'},
  ]
};

// See http://research.pomona.edu/complexnetworks/2016/01/03/louvain-performance-and-self-loops-the-problem/
/*
let nodes = ['A', 'B', 'C', 'D'];
let links = [
  {from: 'A', to: 'B', w:1.0},
  {from: 'B', to: 'A', w:1.0},

  {from: 'B', to: 'C', w:1.0},
  {from: 'C', to: 'B', w:1.0},

  {from: 'C', to: 'A', w:1.0},
  {from: 'A', to: 'C', w:1.0},

  {from: 'C', to: 'D', w:1.0},
  {from: 'D', to: 'C', w:1.0}
];
*/

